### PR TITLE
Only serialize lower triangular part of Hermitian matrices

### LINKED ISSUE #32: Test failure for MHD1280B
When executed for all Matrix Market matrices, [`NEP_mhd_mhd1280b.mtx`](https://math.nist.gov/MatrixMarket/data/NEP/mhd/mhd1280b.html) fails:

```
[ Info: SparseArrays.SparseMatrixCSC{Complex{Float64},Int64}  (1280, 1280)
read and write NEP_mhd_mhd1280b.mtx: Test Failed at /home/szarnyasg/git/MatrixMarket.jl/test/runtests.jl:19
  Expression: new_A == A
   Evaluated: 
  [1   ,    1]  =  2.0+0.0im
  [2   ,    2]  =  0.252506+0.0im
  [4   ,    2]  =  0.000144381-1.11465e-18im
  [33  ,    2]  =  0.101003+0.0im
  [34  ,    2]  =  -0.0252507+0.0im
  [35  ,    2]  =  7.21909e-5-6.04226e-19im
  [36  ,    2]  =  -3.60938e-5+2.08311e-19im
  [3   ,    3]  =  2.0+0.0im
  [2   ,    4]  =  0.000288762+2.2293e-18im
  ⋮
  [1278, 1278]  =  1.49706e-8+0.0im
  [1247, 1279]  =  0.00105197+0.0im
  [1248, 1279]  =  4.96001e-6+0.0im
  [1279, 1279]  =  0.00153412+0.0im
  [1280, 1279]  =  -4.21836e-6+0.0im
  [1247, 1280]  =  -4.94646e-6+0.0im
  [1248, 1280]  =  -2.23563e-8+0.0im
  [1279, 1280]  =  -8.43671e-6+0.0im
  [1280, 1280]  =  1.49706e-8+0.0im == 
  [1   ,    1]  =  2.0+0.0im
  [2   ,    2]  =  0.252506+0.0im
  [4   ,    2]  =  0.000144381-1.11465e-18im
  [33  ,    2]  =  0.101003+0.0im
  [34  ,    2]  =  -0.0252507+0.0im
  [35  ,    2]  =  7.21909e-5-6.04226e-19im
  [36  ,    2]  =  -3.60938e-5+2.08311e-19im
  [3   ,    3]  =  2.0+0.0im
  [2   ,    4]  =  0.000144381+1.11465e-18im
  ⋮
  [1278, 1278]  =  1.49706e-8+0.0im
  [1247, 1279]  =  0.000525987+0.0im
  [1248, 1279]  =  2.48e-6+0.0im
  [1279, 1279]  =  0.00153412+0.0im
  [1280, 1279]  =  -4.21836e-6+0.0im
  [1247, 1280]  =  -2.47323e-6+0.0im
  [1248, 1280]  =  -1.11782e-8+0.0im
  [1279, 1280]  =  -4.21836e-6+0.0im
  [1280, 1280]  =  1.49706e-8+0.0im
Stacktrace:
 [1] top-level scope at /home/szarnyasg/git/MatrixMarket.jl/test/runtests.jl:19
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1156
 [3] include at ./boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:267
 [7] _start() at ./client.jl:436
Test Summary:                       | Fail  Total
read and write NEP_mhd_mhd1280b.mtx |    1      1
Test Summary:                       | Fail  Total
read and write NEP_mhd_mhd1280b.mtx |    1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/szarnyasg/git/MatrixMarket.jl/test/runtests.jl:11
```

It seems some values are doubled, e.g. `A_new` contains
```
[2   ,    4]  =  0.000288762+2.2293e-18im
```
instead of
```
[2   ,    4]  =  0.000144381+1.11465e-18im
```

The full output of the test is available at https://gist.github.com/szarnyasg/2d950447a82935032cd0ddebfafca27e but there were no further test failures.

### PR DESCRIPTION
**Pull request by szarnyasg**
Fixes #32

### CODE REVIEW

File: src/MatrixMarket.jl [hunk 1]
```diff
@@ -161,13 +161,12 @@ function mmwrite(filename, matrix :: SparseMatrixCSC)
...
             "general"
-      symb = issymmetric(matrix)
 
       # write mm header
       write(file, "%%MatrixMarket matrix coordinate $elem $sym\n")
 
-      # only use lower triangular part of symmetric matrices
-      if symb
+      # only use lower triangular part of symmetric and Hermitian matrices
+      if issymmetric(matrix) || ishermitian(matrix)
```
Comment (tkonolige) [inline src/MatrixMarket.jl]: If the matrix is complex and symmetric, but not hermitian, then we will be dropping information. I think the correct test should be `eltype(matrix) <: Complex && ishermitian(matrix) || issymmetric(matrix)`.

Comment (szarnyasg) [reply src/MatrixMarket.jl]: I don't think we will, the matrix can be reconstructed from the information in the file by populating the lower triangle A_ij where i<=j. Then for each element A_ij where i < j, set the value of A_ji.
According to the [specification](https://github.com/JuliaSparse/MatrixMarket.jl/issues/32#issuecomment-513921405), for symmetric, skew-symmetric, and Hermitian matrices "Only entries on or below the main diagonal are provided in the file". This does not distinguish between integer/real/complex values.

I did a quick check on the MatrixMarket matrices but there are only a handful of complex symmatric ones:
```
$ grep 'complex symmetric' *.mtx
Harwell-Boeing_acoust_young1c.mtx:%%MatrixMarket matrix coordinate complex symmetric
Harwell-Boeing_acoust_young2c.mtx:%%MatrixMarket matrix coordinate complex symmetric
Harwell-Boeing_acoust_young3c.mtx:%%MatrixMarket matrix coordinate complex symmetric
Harwell-Boeing_acoust_young4c.mtx:%%MatrixMarket matrix coordinate complex symmetric
NEP_gedney_dwg961a.mtx:%%MatrixMarket matrix coordinate complex symmetric
NEP_gedney_dwg961b.mtx:%%MatrixMarket matrix coordinate complex symmetric
```

There are examples for both redundant and non-redundant storage. For example, [YOUNG1C](https://math.nist.gov/MatrixMarket/data/Harwell-Boeing/acoust/young1c.html) has duplicate value:
```
%%MatrixMarket matrix coordinate complex symmetric
841 841 4089
1 1 -2.1846000000000e+02  0.0000000000000e+00
2 1  6.4000000000000e+01  0.0000000000000e+00
30 1  6.4000000000000e+01  0.0000000000000e+00
1 2  6.4000000000000e+01  0.0000000000000e+00
...
```
But [DWG961A](https://math.nist.gov/MatrixMarket/data/NEP/gedney/dwg961a.html) does not any:
```
%%MatrixMarket matrix coordinate complex symmetric
% Generated 14-Nov-96
961 961 2055
1 1 -49.1537  4797.68
2 1 -24.0559  992.499
3 1 -24.0573  992.384
2 2 -25.0978  3805.18
3 2 -12.5475  1902.7
...
```

Comment (tkonolige) [reply src/MatrixMarket.jl]: You are totally correct here.

Interestingly, YOUNG1C appears to be malformed according to the spec.
